@startuml "Mudl Document Web"

' left to right direction

rectangle "[[liverpool.md]]" #line.dashed {
  rectangle "[[http://www.wikidata.org/entity/Q24826 Liverpool]]" as liverpool
  rectangle "[[http://www.wikidata.org/entity/Q21 England]]" as england
  liverpool --> england : [[partOf part of]]
}

rectangle "[[the-beatles.md]]" #line.dashed {
  rectangle "[[the-beatles The Beatles]]" as the_beatles
  rectangle "[[the-beatles#john John]]" as john
  rectangle "[[yoko Yoko]]" as yoko
  rectangle "[[http://www.wikidata.org/entity/Q24826 Liverpool]]" as beatles_liverpool
  the_beatles --> john : [[see_also see also]]
  john --> beatles_liverpool : [[birthPlace birth place]]
  john --> yoko : [[spouse]]
  the_beatles --> beatles_liverpool : [[foundingLocation founded in]]
  beatles_liverpool *--* liverpool
}

rectangle "[[yoko.md]]" #line.dashed {
    rectangle "[[yoko Yoko]]" as yoko_ono
    rectangle "[[http://vocab.getty.edu/aat/300025103 artist]]" as artist
    rectangle "[[http://www.wikidata.org/entity/Q7473516 Tokyo]]" as tokyo
    yoko *--* yoko_ono
    yoko_ono --> artist : [[additionalType classified as]]
    yoko_ono --> tokyo : [[birthPlace birth place]]
}


@enduml
